version: "3.9"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "root"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - 127.0.0.1:5432:5432